<?php

class News extends Article
{
    private $short_description;

    public function __construct($tit = "", $data = "", $cont = "", $sd = '')
    {
        parent::__construct($tit, $data, $cont);
        $this->short_description = $sd;
    }

    public function show()
    {
        parent::show(); // TODO: Change the autogenerated stub
        echo 'Short Description: ' . $this->short_description . "<br />";
    }

    public function setShortDescription($sd)
    {
        $this->short_description = $sd;
    }


    public function getShortDescription()
    {
        return $this->short_description;
    }

}